// This file is auto-generated by @hey-api/openapi-ts

export type AiModelResponse = {
    id: number;
    name: string;
    provider: src__api__schemas__ai_models__AiProviderResponse;
};

export type AiProviderModelResponse = {
    id: number;
    name: string;
};

export type Body_upload_file_api_files_upload_post = {
    file: (Blob | File);
};

export type ChatCompletionRequest = {
    model_id: number;
    messages: Array<ChatMessageRequest>;
    chat_id?: string | null;
    options?: DefaultResponseGenerationOptions | null;
};

export type ChatListItemResponse = {
    id: string;
    title: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    pinned: boolean;
};

export type ChatMessageRequest = {
    role: 'user' | 'assistant';
    content: string;
    attachments?: Array<(string)> | null;
};

export type role = 'user' | 'assistant';

export type ChatMessageResponse = {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    attachments?: Array<(string)> | null;
    created_at: string;
};

export type ChatResponse = {
    id: string;
    title: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    pinned: boolean;
    messages?: Array<ChatMessageResponse>;
};

/**
 * Options for text generation
 */
export type DefaultResponseGenerationOptions = {
    /**
     * Controls randomness. Higher values (e.g., 0.8) make output more random, lower values (e.g., 0.2) make it more deterministic.
     */
    temperature?: number;
    /**
     * Maximum number of tokens to generate in the response.
     */
    max_tokens?: number;
};

export type FileResponse = {
    /**
     * The id of the file
     */
    file_id: string;
    /**
     * The name of the file
     */
    filename: string;
    /**
     * The content type of the file
     */
    content_type: string;
};

export type GoogleAuthRequest = {
    token: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TokenResponse = {
    access_token: string;
};

export type UpdateChatTitleRequest = {
    title: string;
};

export type UserResponse = {
    id: string;
    email: string;
    first_name?: string | null;
    last_name?: string | null;
    profile_image_url?: string | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type src__api__schemas__ai_models__AiProviderResponse = {
    id: number;
    name: string;
    slug: string;
};

export type src__api__schemas__ai_provider__AiProviderResponse = {
    id: number;
    name: string;
    slug: string;
    models?: Array<AiProviderModelResponse>;
};

export type GetHealthLiveResponse = unknown;

export type GetApiAiProvidersResponse = Array<src__api__schemas__ai_provider__AiProviderResponse>;

export type GetApiChatsResponse = Array<ChatListItemResponse>;

export type PostApiChatsResponse = ChatResponse;

export type GetApiChatsByChatIdData = {
    chatId: string;
};

export type GetApiChatsByChatIdResponse = ChatResponse;

export type DeleteApiChatsByChatIdData = {
    chatId: string;
};

export type DeleteApiChatsByChatIdResponse = unknown;

export type PostApiChatsConversationData = {
    requestBody: ChatCompletionRequest;
};

export type PostApiChatsConversationResponse = unknown;

export type PatchApiChatsByChatIdTitleData = {
    chatId: string;
    requestBody: UpdateChatTitleRequest;
};

export type PatchApiChatsByChatIdTitleResponse = unknown;

export type PatchApiChatsByChatIdPinData = {
    chatId: string;
};

export type PatchApiChatsByChatIdPinResponse = unknown;

export type PostApiAuthGoogleData = {
    requestBody: GoogleAuthRequest;
};

export type PostApiAuthGoogleResponse = TokenResponse;

export type GetApiUsersCurrentResponse = UserResponse;

export type GetApiAiModelsResponse = Array<AiModelResponse>;

export type PostApiFilesUploadData = {
    formData: Body_upload_file_api_files_upload_post;
};

export type PostApiFilesUploadResponse = FileResponse;

export type GetApiFilesByFileIdData = {
    fileId: string;
};

export type GetApiFilesByFileIdResponse = unknown;

export type GetApiUtilizationResponse = unknown;

export type GetApiUtilizationLimitsResponse = unknown;

export type $OpenApiTs = {
    '/health/live': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/ai-providers': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<src__api__schemas__ai_provider__AiProviderResponse>;
            };
        };
    };
    '/api/chats/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ChatListItemResponse>;
            };
        };
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: ChatResponse;
            };
        };
    };
    '/api/chats/{chat_id}': {
        get: {
            req: GetApiChatsByChatIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChatResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiChatsByChatIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/conversation': {
        post: {
            req: PostApiChatsConversationData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/{chat_id}/title': {
        patch: {
            req: PatchApiChatsByChatIdTitleData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/{chat_id}/pin': {
        patch: {
            req: PatchApiChatsByChatIdPinData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/google': {
        post: {
            req: PostApiAuthGoogleData;
            res: {
                /**
                 * Successful Response
                 */
                200: TokenResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/users/current': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserResponse;
            };
        };
    };
    '/api/ai-models': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<AiModelResponse>;
            };
        };
    };
    '/api/files/upload': {
        post: {
            req: PostApiFilesUploadData;
            res: {
                /**
                 * Successful Response
                 */
                200: FileResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/files/{file_id}': {
        get: {
            req: GetApiFilesByFileIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/utilization': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/utilization/limits': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};